import {newEnsembleGame,actEnsemble,autoPlayEnsemble,rankings,canRehearse,companyPoints} from './ensemble-engine.mjs';

const root=document.querySelector('#app');
const KEY='ensemble-debut-save-v1';
const e=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
// The card face is painted from a css custom property, and a url() inside one of those resolves
// against the stylesheet rather than the page, so build an absolute url from the document instead.
const portraitPath=card=>card.kind==='actor'?`dlc/actor-agency/portraits/${card.id}.jpg`:`portraits/${card.id}.jpg`;
const portrait=card=>new URL(portraitPath(card),document.baseURI).href;
let state=null,selectedId=null,focus='vocal',promo=0,gate=true,error='';
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved?.mode==='ensemble'&&Array.isArray(saved.players))state=saved;}catch{}
if(state){try{autoPlayEnsemble(state);selectedId=state.players[state.current]?.cards[0]?.id||null;gate=['rehearsal','stage'].includes(state.phase);}catch{state=null;}}
const save=()=>state?localStorage.setItem(KEY,JSON.stringify(state)):localStorage.removeItem(KEY);
const player=()=>state.players[state.current];
const selected=()=>player()?.cards.find(card=>card.id===selectedId)||player()?.cards[0];
const total=card=>card.vocal+card.creativity;

function cardView(card,owner=false){return `<button type="button" class="debut-card ${selectedId===card.id&&!owner?'chosen':''}" data-select="${e(card.id)}" style="--card-image:url('${portrait(card)}')">
  <span class="debut-card-kind">${card.kind==='actor'?'ACTOR':'SINGER'}</span><span class="debut-card-face"></span><span class="debut-card-text"><b>${e(card.name)}</b><small>${e(card.genre)}</small><span>♫ ${card.vocal}　✦ ${card.creativity}　★ ${card.fans}</span></span>${card.fatigue?`<span class="debut-fatigue">FATIGUE ${card.fatigue}</span>`:''}</button>`;}

function setup(){return `<main class="debut-shell debut-title"><div class="debut-title-copy"><span class="debut-eyebrow">RECORD LABEL RIVALS · COED STAGE DLC</span><h1>DEBUT<br><em>NIGHT</em></h1><p>Bring singers and actors to one stage. Win the rehearsal spaces, climb the rankings, and fill seven debut seats with your company cards.</p>
<form id="ensemble-setup"><b>CHOOSE 2–4 COMPANIES</b>${[0,1,2,3].map(index=>`<label><i>0${index+1}</i><input name="name${index}" value="${['Your Company','Rival Company','Third Company','Fourth Company'][index]}" maxlength="24"><select name="type${index}"><option value="human" ${index===0?'selected':''}>Human</option><option value="ai" ${index===1?'selected':''}>Computer</option><option value="off" ${index>1?'selected':''}>Off</option></select></label>`).join('')}<button class="gold-button" type="submit">OPEN THE SEASON ➜</button></form><a class="debut-back" href="./">← MAIN GAME</a></div><div class="debut-title-art"></div></main>`;}

function scoreBar(){return `<header class="debut-hud"><div class="debut-mark"><span>◉</span> DEBUT <b>NIGHT</b></div><div class="episode">EPISODE <strong>${state.round}</strong><small>/ 5</small></div><div class="companies">${state.players.map(company=>`<div style="--company:${company.color}" class="company-chip ${company.id===state.current&&['rehearsal','stage'].includes(state.phase)?'active':''}"><b>${e(company.name)}</b><small>${company.ai?'CPU':'HUMAN'} · $${company.cash}</small></div>`).join('')}</div><a href="./" title="Main game">⌂</a><button data-action="reset" title="New season">↻</button></header>`;}

function rankingRail(){return `<aside class="ranking-rail"><h3>LIVE RANKING</h3><div>${rankings(state).slice(0,9).map((card,index)=>`<div class="rank-line ${index<7?'debut-bound':''}" style="--company:${card.companyColor}"><span>${String(index+1).padStart(2,'0')}</span><img src="${portrait(card)}" alt=""><b>${e(card.name)}</b><small>★ ${card.fans}</small></div>`).join('')}</div><p>TOP 7 DEBUT · HIGHEST RANKS SCORE MORE</p></aside>`;}

function rehearsal(){const card=selected();const options=[['vocal','VOCAL BOOTH','+2 to Vocal stage score'],['dance','CHOREOGRAPHY','+2 to Dance stage score'],['story','CAMERA REHEARSAL','+2 to Story stage score'],['rest','RECOVERY','−3 Fatigue · +1 any focus']];return `<div class="debut-scene"><span class="debut-overline">EPISODE ${state.round} / REHEARSAL</span><h2>CLAIM YOUR SPACE</h2><p>Place one card at an open station. Only one company can claim each specialist station this episode.</p><div class="debut-animation debut-animation-stage"></div><div class="rehearsal-options">${options.map(([id,title,detail])=>`<button data-station="${id}" ${canRehearse(state,id)?'':'disabled'}><span>${id==='rest'?'✦':id==='vocal'?'♫':id==='dance'?'◈':'◉'}</span><b>${title}</b><small>${canRehearse(state,id)?detail:'OCCUPIED'}</small></button>`).join('')}</div><div class="debut-instruction">SELECT A CARD, THEN CLAIM A SPACE</div></div>`;}

function stage(){const card=selected();return `<div class="debut-scene"><span class="debut-overline">EPISODE ${state.round} / LIVE STAGE</span><h2>OWN THE MOMENT</h2><p>Choose a card and one strength to showcase. Spend up to $3 on promotion. Submissions remain sealed until everyone has performed.</p><div class="debut-animation debut-animation-stage"></div><div class="stage-controls"><div class="focus-picker">${[['vocal','♫','VOCAL'],['dance','◈','DANCE'],['story','◉','STORY']].map(([id,symbol,title])=>`<button class="${focus===id?'selected':''}" data-focus="${id}"><span>${symbol}</span><b>${title}</b><small>${card?id==='vocal'?card.vocal:id==='dance'?card.creativity:Math.round(total(card)/2)+(card.kind==='actor'?1:0):0} base</small></button>`).join('')}</div><div class="promo-picker"><span>PROMOTION</span><button data-action="promo-down">−</button><strong>$${promo}</strong><button data-action="promo-up">+</button></div><button class="gold-button perform-button" data-action="perform">LOCK IN PERFORMANCE ➜</button></div></div>`;}

function results(){return `<div class="debut-scene result-scene"><span class="debut-overline">EPISODE ${state.round} / RANKING REVEAL</span><h2>THE STAGE HAS SPOKEN</h2><div class="debut-animation debut-animation-seats"></div><div class="episode-results">${state.results.map((result,index)=>`<div><span>#${index+1}</span><b>${e(result.name)}</b><small>${e(result.company)} · ${e(result.focus.toUpperCase())}</small><strong>${result.score} + ${result.bonus}★</strong></div>`).join('')}</div><button class="gold-button results-next" data-action="continue">${state.round===5?'REVEAL DEBUT LINEUP':'NEXT EPISODE'} ➜</button></div>`;}

function finale(){return `<div class="debut-scene finale-scene"><span class="debut-overline">THE FINAL SEVEN</span><h2>THE DEBUT LINEUP</h2><div class="debut-animation debut-animation-seats"></div><div class="final-seven">${state.debut.map(card=>`<div style="--company:${card.companyColor}"><span>#${card.rank}</span><img src="${portrait(card)}" alt=""><b>${e(card.name)}</b><small>${e(card.companyName)}</small><strong>${card.points} PTS</strong></div>`).join('')}</div><div class="final-score">${state.players.map(company=>`<span style="--company:${company.color}"><b>${e(company.name)}</b><strong>${companyPoints(state,company.id)} PTS</strong><small>${state.debut.filter(card=>card.companyId===company.id).length} DEBUT SEATS</small></span>`).join('')}</div><h3>${e(state.winnerIds.map(id=>state.players[id].name).join(' & '))} WINS</h3><button class="gold-button" data-action="reset">PLAY ANOTHER SEASON ➜</button></div>`;}

function hand(){if(!['rehearsal','stage'].includes(state.phase))return '';return `<section class="debut-hand"><div class="debut-hand-heading"><span>${e(player().name)} · YOUR CAST</span><small>2 SINGERS + 2 ACTORS · CLICK TO SELECT</small></div><div class="debut-cards">${player().cards.map(card=>cardView(card)).join('')}</div></section>`;}
function gateView(){return gate&&['rehearsal','stage'].includes(state.phase)&&!player().ai?`<div class="debut-gate"><div><span>PASS THE DEVICE</span><h2>${e(player().name)}</h2><p>Your roster and stage choice stay private until you take your seat.</p><button class="gold-button" data-action="ready">TAKE YOUR SEAT ➜</button></div></div>`:'';}
function render(){if(!state){root.innerHTML=setup();return;}root.innerHTML=`<main class="debut-shell game-active">${scoreBar()}<div class="debut-body">${rankingRail()}<section class="debut-board">${state.phase==='rehearsal'?rehearsal():state.phase==='stage'?stage():state.phase==='results'?results():finale()}</section></div>${hand()}${error?`<div class="debut-error">${e(error)}</div>`:''}${gateView()}</main>`;}
function afterAction(action){try{actEnsemble(state,action);autoPlayEnsemble(state);selectedId=player()?.cards[0]?.id||null;promo=0;gate=['rehearsal','stage'].includes(state.phase);error='';save();render();}catch(exception){error=exception.message;render();}}

root.addEventListener('submit',event=>{if(event.target.id!=='ensemble-setup')return;event.preventDefault();const form=new FormData(event.target);const players=[0,1,2,3].filter(index=>form.get(`type${index}`)!=='off').map(index=>({name:form.get(`name${index}`),ai:form.get(`type${index}`)==='ai'}));try{state=newEnsembleGame({players});autoPlayEnsemble(state);selectedId=player().cards[0].id;gate=true;error='';save();render();}catch(exception){error=exception.message;alert(error);}});
root.addEventListener('click',event=>{const button=event.target.closest('button');if(!button||button.disabled)return;if(button.dataset.select){selectedId=button.dataset.select;render();return;}if(!state)return;if(button.dataset.action==='ready'){gate=false;render();return;}if(button.dataset.action==='reset'){if(!confirm('Start a new debut season?'))return;state=null;save();render();return;}if(gate)return;if(button.dataset.station){afterAction({type:'rehearse',cardId:selected()?.id,station:button.dataset.station});return;}if(button.dataset.focus){focus=button.dataset.focus;render();return;}switch(button.dataset.action){case'promo-down':promo=Math.max(0,promo-1);render();break;case'promo-up':promo=Math.min(3,player().cash,promo+1);render();break;case'perform':afterAction({type:'perform',cardId:selected()?.id,focus,promo});break;case'continue':afterAction({type:'continue'});break;}});
render();
